# os: linux and sudo: false is assumed, which means it is using container-based Ubuntu 12.04
language: python
cache: pip
# build matrix: different python and pandoc versions
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.6-dev" # 3.6 development branch
  # - "nightly" # currently points to 3.7-dev
  # pypy (version info from [Changelogs â€” PyPy documentation](http://doc.pypy.org/en/latest/index-of-whatsnew.html))
  - "pypy"  # PyPy2.7 5.3.1 (CPython 2.7 compatible)
  - "pypy3" # PyPy3 2.4.0 (CPython 3.2 compatible)
env:
  # - pandocVersion=1.13.2
  # - pandocVersion=1.14
  # - pandocVersion=1.14.0.1
  # - pandocVersion=1.14.1
  # - pandocVersion=1.15
  # - pandocVersion=1.15.0.5
  # - pandocVersion=1.15.0.6
  # - pandocVersion=1.15.1
  # - pandocVersion=1.15.2
  # - pandocVersion=1.16
  # - pandocVersion=1.16.0.1
  # - pandocVersion=1.16.0.2
  # - pandocVersion=1.17
  # - pandocVersion=1.17.0.1
  # - pandocVersion=1.17.0.2
  # - pandocVersion=1.17.1
  # - pandocVersion=1.17.2
  # - pandocVersion=1.18
  # - pandocVersion=1.19.2.1
  # - pandocVersion=2.0.6
  - pandocVersion=latest
matrix:
  allow_failures:
    # - python: "3.3"
    # - python: "3.6-dev"
    # - python: "nightly"
    # - python: "pypy3"
    # - env: pandocVersion=1.13.2
    # - env: pandocVersion=1.14
    # - env: pandocVersion=1.14.0.1
    # - env: pandocVersion=1.14.1
    # - env: pandocVersion=1.15
    # - env: pandocVersion=1.15.0.5
    # - env: pandocVersion=1.15.0.6
    # - env: pandocVersion=1.15.1
    # - env: pandocVersion=1.15.2
    # - env: pandocVersion=latest
  fast_finish: true
# install dependencies
install:
  # latest pip dropped support for py3.2, which is the version of python in pypy3
  - if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]]; then pip install -U pip; fi
  - pip install -e .[test]
  # pandoc
  - downloadUrl=$(python -c 'import requests, sys; v = sys.argv[1]; url = "https://api.github.com/repos/jgm/pandoc/releases/" + (v if v == "latest" else ("tags/" + v)); print(next(i["browser_download_url"] for i in requests.get(url).json()["assets"] if i["name"][-3:] == "deb"))' $pandocVersion) &&
    wget $downloadUrl &&
    sudo dpkg -i ${downloadUrl##*/}
# command to run tests
script:
  # this kind of defeat CI, but they might not provide identical outputs...
  - make -j4 test ERRORCODE=0
after_success:
  - if [[ "$pandocVersion" == "latest" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls; else printf "skip coveralls"; fi
deploy:
  provider: pypi
  user: ickc
  password: $pypi_password
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    tags: true
    python: "3.6"
    condition: $pandocVersion = latest
env:
  global:
    secure: "ldequnb5RP6xFsgwo4AOun12RURGFqeInrY162AMS1tVg0Wkq8JF+wTC30B4UjUxbHKmo5uRlILUA1E7mttAcKlOgITkFbdE+bNj0PaxfArUj8lN5ynyZuWZyUx/9zmuvL+BrA2hmTBsbaEWticnArijwXMrzpB6gvcitGOI9rky3n7ry9WZfCtOcFXNsjW29N+gbJ/K3yN4NadAuLSBVmRerkKuHC2OuWSgrq/I4naerjTm3JC5HXNEunojNWEuhcSWEoZfHpFUjn9ttjggKmGBNJS/sQU8B2/a5X9RtTI4FL8nO/jizm29nJVXc330xxJzaKXX0dIGJCm5SbL7yUQU3rQ7UHqV6G7OM3lgt3rfP2ph6WycEI1wnn5SVfm5E4+5BYsx1ApLj19lhHhXGefie5sKrVrcz993iXoIiJoIAbhU974vjOMBh6YwQLqmHbdJS86HUTAuQfxrznGdnZbQ95m0gjfmFMZedEEFtSvtiaK80wSgIwqPPThSAzz3NoSE+uPAkoJdJlbQa1tPVrWJXHSmnmw9q66/dyQ3OXShDgnq7rQ9yLCtKrQpdOFxXmmyvTA/UKl329T+bfff38szZLHOs/Hkqa0TFbvYZvJnQ7Gz+6Z7y4zmeSOBMRirynqWbqQfG6l7LSH8c/5xLw11xriiFf9w8TJ8+Ebv71g="
